### ISSUE TITLE
Faster Mouse Scrolling

### ISSUE THREAD

**Issue by 73** [hugolabe/Wike#1]
Nice idea and good feature set!

However, when I am scrolling with the mouse, it feels way too slow (same problem with epiphany).
Wike 1.1.0 from Flathub

**Comment by hugolabe** [comment]
Wike uses webkit (same as Epiphany) to display content. Therefore, the scrolling speed depends of webkit.

In my case, the scrolling speed seems similar to any web browser.

**Comment by 73** [comment]
I thought so. Thanks.

**Comment by K4LCIFER** [comment]
> However, when I am scrolling with the mouse, it feels way too slow

are you referring to the weird deceleration in scrolling speed when you near the end of the page?
I also noticed weird behaviour when putting my scrollwheel in freewheel mode and spinning it fast: it would accelerate into its scrolling speed, reach max towards the middle, and then decelerate towarrds the end. I expect it to just whip as fast as I can scroll.
