### ISSUE TITLE
Restore tabs

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#100]
It would be convenient if Wike would restore the tabs so it is easy to get back to the articles you had open after you restart the computer.

**Comment by hugolabe** [comment]
This could give performance issues if many tabs are opened at the same time. I will do some tests when I have time.

**Comment by vanillajonathan** [comment]
I can have hundreds of tabs open in Firefox and Chrome without much of performance issues. The tabs could use lazy loading and only load the active one, then load the other tabs when switched to.
