### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by Kekun** [hugolabe/Wike#104]
That'd be great to allow offline support, by pre-downloading articles, a bit like OSDAnd for maps.

**Comment by hugolabe** [comment]
#15

**Comment by Kekun** [comment]
Thanks, though I don't think saving articles and having a pre-downloaded articles database isn't the same.

**Comment by hugolabe** [comment]
Sorry @Kekun. Maybe I have not understood you well (my English knowledge is very limited). I understand that you mean having some articles saved locally. That seems complicated since Wike works as a browser, using Webkit to show the mobile version of Wikipedia on a webview.

**Comment by Kekun** [comment]
I was thinking about something like this: https://es.wikipedia.org/wiki/Wikipedia:Descargas

**Comment by hugolabe** [comment]
I know Kiwix. It works by downloading all wikipedia to a file in ZIM format. This is something very different from how Wike works and supporting it would require a complete rewriting of the app.

On the other hand, for those who need offline access, there is already the [Kiwix application](https://flathub.org/apps/details/org.kiwix.desktop) itself.

**Comment by TheEvilSkeleton** [comment]
> I know Kiwix. It works by downloading all wikipedia to a file in ZIM format. This is something very different from how Wike works and supporting it would require a complete rewriting of the app.

I apologize for reviving this issue. I'm currently working on a fork of Wike to bring in ZIM support (see https://github.com/hugolabe/Wike/compare/master...TheEvilSkeleton:Wike:libzim). It's currently heavily work in progress, but I plan to refactor the codebase to allow different formats. Would you like me to upstream some of these changes, if not all?
