### ISSUE TITLE
Wike article scrolling is slow / not smooth (on Wayland with 4K screen)

### ISSUE THREAD

**Issue by nekohayo** [hugolabe/Wike#107]
With Wike 1.8.1 from the Fedora 37 repositories, visiting [this article](https://en.wikipedia.org/wiki/Leopard_2) and trying to croll it by clicking and holding + dragging the scrollbar widget (with the left mouse button), with a maximized Wike window on a 4K display at 2x scale (HiDPI) on Wayland, the scrolling is noticeably not smooth, unlike in Firefox.

I suspect this would be a WebKitGTK performance issue, but I'm filing it here just in case. Attached is a syscap file that you can open and analyze with the [Sysprof](https://wiki.gnome.org/Apps/Sysprof) app: [wike-scrolling-leopard2-article.zip](https://github.com/hugolabe/Wike/files/10704117/wike-scrolling-leopard2-article.zip)

This is using Intel Kabylake graphics.

**Comment by hugolabe** [comment]
Scrolling through the article view is handled by Webkit. There's not much I can do about it.

**Comment by xfgusta** [comment]
Hi @nekohayo,

I've updated [wike](https://src.fedoraproject.org/rpms/wike) to 1.8.3, which includes WebKit2 4.1. Although I can't reproduce the issue myself, this might help.
