### ISSUE TITLE
Browser extension to open Wikipedia links in Wike

### ISSUE THREAD

**Issue by xplosionmind** [hugolabe/Wike#108]
It would be great if a browser extension could be provided to automatically open Wikipedia links in Wike!

Maybe it would be nice to consider implementing this feature in already existing redirecting extensions, like [LibRedirect](https://libredirect.github.io).

[Issue in LibRedirect repo](https://codeberg.org/LibRedirect/libredirect/issues/79)

**Comment by xplosionmind** [comment]
> Is there any specific url I can use? like with FreeTube I can do `freetube://https://youtu.be/K5E8eeyAQLM`

From https://codeberg.org/LibRedirect/libredirect/issues/79#issuecomment-833323

**Comment by hugolabe** [comment]
It could be interesting. Personally I don't have knowledge about extension development nor the time to dedicate myself to this.

**Comment by hugolabe** [comment]
> > Is there any specific url I can use? like with FreeTube I can do `freetube://https://youtu.be/K5E8eeyAQLM`
> 
> From https://codeberg.org/LibRedirect/libredirect/issues/79#issuecomment-833323

I don't really know what this URL refers to, but I don't know if it would be appropriate to add Wike to LibRedirect. From what I've seen its purpose is to redirect certain services to other more privacy-focused options. This is not the case with Wike, since it accesses Wikipedia in the same way that a browser does.

**Comment by xplosionmind** [comment]
> I don't know if it would be appropriate to add Wike to LibRedirect. From what I've seen its purpose is to redirect certain services to other more privacy-focused options. This is not the case with Wike, since it accesses Wikipedia in the same way that a browser does.

Regardless of the purpose of the extension, if its developers are willing to implement this feature in the upstream, it would still be better than coding a Wike-specific extension from scratch.

---

> I don't really know what this URL refers to

it refers to opening YouTube links [in FreeTube app](https://freetubeapp.io)

**Comment by hugolabe** [comment]
I close this, since the possible development of an extension would in any case be external to the app.

**Comment by ManeraKai** [comment]
This "possible development of an extension" is already developed by us [LibRedirect](https://libredirect.github.io) :) So plz can you implement this?

**Comment by ManeraKai** [comment]
This "possible development of an extension" is already done by us LibRedirect :). So can you plz implement this?
