### ISSUE TITLE
More convenient keyboard shortcut to search for articles

### ISSUE THREAD

**Issue by apandada1** [hugolabe/Wike#11]
In a laptop, one needs to type <kbd> fn </kbd> + <kbd> f2 </kbd> to search for articles.
It is quite awkward to quickly type this key pair (it is hard to quickly and accurately reach <kbd> f2 </kbd> with one finger, after pressing <kbd> fn </kbd> with another finger).

Something like <kbd> ctrl </kbd> + <kbd> shift </kbd> + <kbd> f </kbd> would be more convenient.

**Comment by hugolabe** [comment]
How about <kbd>Ctrl</kbd> + <kbd>K</kbd>?
It's simpler and is the shortcut to the search bar in web browsers.

**Comment by apandada1** [comment]
> How about <kbd>Ctrl</kbd> + <kbd>K</kbd>?
That is certainly more convenient than <kbd>fn</kbd>+<kbd>f2</kbd>.
