### ISSUE TITLE
2.0 looks amazing!

### ISSUE THREAD

**Issue by davidskeck** [hugolabe/Wike#120]
I just had to jump in to say thank you so much for your work on this. Easily my favorite Wikipedia app. 2.0 looks absolutely fantastic. Wonderful job!

I'll close this issue now, but didn't want the release to go by without commenting on how excellent it is. Thanks again!

**Comment by hugolabe** [comment]
Thanks @davidskeck !
Knowing that other people appreciate the app is a great motivation to keep working on it.
