### ISSUE TITLE
Offline cache

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#121]
Alice is in the arctic without any internet connectivity. Bob is on a boat and have no internet connectivity. Clare is in the jungle without any internet connectivity. Dave is in the desert without any internet connectivity. They all need information!

Wike could offline cache visited articles and fallback to that offline cache if it cannot connect to Wikipedia.

**Comment by hugolabe** [comment]
This has already been discussed other times: #15 #104 

It's quite complicated (as Wike works) and is outside the scope of the app. There are [other alternatives](https://flathub.org/apps/details/org.kiwix.desktop) for those who require offline access to Wikipedia.

**Comment by vanillajonathan** [comment]
It seems there is a library for this.
https://requests-cache.readthedocs.io

**Comment by hugolabe** [comment]
> It seems there is a library for this. https://requests-cache.readthedocs.io

Requests is only used to perform searches and something else, but not to get the content of the articles. The article view is nothing more than the Wikipedia web page tweaked by css injection.

**Comment by vanillajonathan** [comment]
Maybe [`set_enable_offline_web_application_cache`](https://webkitgtk.org/reference/webkit2gtk/stable/method.Settings.set_enable_offline_web_application_cache.html), [`set_enable_page_cache`](https://webkitgtk.org/reference/webkit2gtk/stable/method.Settings.set_enable_page_cache.html) or [`WebContext.new_with_website_data_manager`](https://webkitgtk.org/reference/webkit2gtk/stable/ctor.WebContext.new_with_website_data_manager.html) could be of interest.
