### ISSUE TITLE
Shortcut Ctrl+C mapped to unusual action

### ISSUE THREAD

**Issue by cdelledonne** [hugolabe/Wike#126]
Hi, thanks a lot for this great app!

I was trying to copy some text from within an article when I realized that the <kbd>Ctrl</kbd> + <kbd>C</kbd> keyboard shortcut is mapped to "Table of contents". I believe it's pretty unusual for such a shortcut to not be mapped to "Copy text".

Would you consider mapping <kbd>Ctrl</kbd> + <kbd>C</kbd> to the standard copy action? I don't really have a better suggestion for what to use for "Table of contents" though :).

Thanks.

**Comment by hugolabe** [comment]
You are right. I didn't realize it interfered with the standard shortcut for copying text. I will change it.

Thanks!

**Comment by cdelledonne** [comment]
That's awesome, thanks!

**Comment by hugolabe** [comment]
I've changed the Table of Contents shortcut to <kbd>Ctrl</kbd>+<kbd>I</kbd> (for Index). You can now copy text using <kbd>Ctrl</kbd>+<kbd>C</kbd>.

8e1ca6893013f647b3105ad35febdbd422bfe77e
