### ISSUE TITLE
Feature Proposal - let user chose the preferred language

### ISSUE THREAD

**Issue by ralxxx** [hugolabe/Wike#127]
Wike is a great and helpful too. 

For now, it seems English is set as sole principal language. When opening Wike, the page opening is English. Ideally this preset can be cchanged somwhere within the settings.

**Comment by hugolabe** [comment]
I don't understand what you mean.

In Wike you can choose the languages ​​you want to use and set any of them as default, using the search settings popover.

![languages-select](https://user-images.githubusercontent.com/18441950/233188908-6fed2970-b695-48b1-93cc-3fb17c876dd0.png)

**Comment by ralxxx** [comment]
Hm, not sure what you mean. Wike in my context seems to look a bit different (using Fedora 38). 

- In the preferences there's a language section for chosing preferred languages. 
- And then I have the language symbol were I can swap between the languages I have chosen. 
- 
- But I did not find anywhere an option to select the preferred language.

![Wika-lng-screenshot-1](https://user-images.githubusercontent.com/36100882/233192214-d4e68e9b-a20f-4f4c-a346-5a051a122bdd.png)
![Wika-lng-screemshot-2](https://user-images.githubusercontent.com/36100882/233192206-9684ad18-90a0-421e-a4c5-2b733a6d69f4.png)

**Comment by hugolabe** [comment]
Ah, you are on version 1.8. In this version to access the search settings popover you have to press the gear icon in the search input.

![wike1](https://user-images.githubusercontent.com/18441950/233281136-14640dc8-44ed-479f-b034-784e93d73265.png)

I have recently released version 2.0 which has quite a few UI changes. Currently in Fedora 38 you have version 2.0 at flatpak, while the RPM package is still at version 1.8.

**Comment by ralxxx** [comment]
@hugolabe Thanks! I actually did not pay attention that the version I installed (from the Fedora repository) is not the latest). Indeed, v2.0 behaves pretty different. I'll clome my comment in a minute. 

Another observation with v2.0 when using another language (not English) as first language for Wike: 

Gnome's built-in search tool works well with Wike - unfortunately it seems to refer to the English language Wikipedia only.  

![Screenshot from 2023-04-20 09-35-06](https://user-images.githubusercontent.com/36100882/233294145-9160b902-8a0c-418a-b3ab-0e611e7976fa.png)

**Comment by hugolabe** [comment]
Desktop searches are performed in the language you have chosen as the default in the app.

You can also search in other languages ​​using a prefix (a hyphen followed by the language code). For example, to search in German you would type: `-de term_to_search`

**Comment by ralxxx** [comment]
Didn't know. Thanks for the quick reply and thanks for the great piece of software.
