### ISSUE TITLE
Missing icons on KDE

### ISSUE THREAD

**Issue by spoorun** [hugolabe/Wike#133]
When running on KDE (with Wayland) the icons are missing in at least 3 places.
See attached image. Missing icons highlighted.

![wike-missing-icons-kde2](https://user-images.githubusercontent.com/627140/234258525-b74318c9-e77b-4f89-8494-451ba47f3119.png)

**Comment by apandada1** [comment]
1. Which version of Wike are you using?
2. How did you install Wike?
3. Which operating system?

**Comment by xfgusta** [comment]
I can reproduce it on Fedora Linux 38 and Wike 2.0.1 (built from source). It looks like we're using the Breeze icon, which doesn't include some icons like sidebar-show-right-symbolic. Changing Breeze to Adwaita works, but it's not ideal.

![image](https://user-images.githubusercontent.com/66979446/234740349-1c402b71-e0e9-45a3-ab6b-91c801f19c45.png)

**Comment by hugolabe** [comment]
Tested on Manjaro KDE (live image) works fine for me.

![Screenshot_20230426_152436](https://user-images.githubusercontent.com/18441950/234802997-3943f4b2-6630-4454-9546-d916f84bcd4c.png)

> It looks like we're using the Breeze icon, which doesn't include some icons like sidebar-show-right-symbolic.

However, it seems strange that such common icons as the printer one are not displayed. And the rest of the icons, which are shown correctly on the screenshot, correspond to the Adwaita set. Shouldn't Breezie's be showing?

> A possible fix would be to include these icons in the same way as done here: https://github.com/hugolabe/Wike/tree/master/data/icons/scalable/actions.

Yes, this would fix any icon issues. But in this case I think it would be best to install all the application icons as gresources, to avoid mixing different themes in case you are using a different set than Adwaita.

**Comment by apandada1** [comment]
![image](https://user-images.githubusercontent.com/3063132/234993546-64c4904f-3e5f-489d-9616-43f568c14561.png)

![image](https://user-images.githubusercontent.com/3063132/234993905-86672824-a06a-4c2a-882c-64468da3f7bc.png)


In Kubuntu 22.04 (Wike installed via flatpak), I can see the printer icon and new tab icon, but not some other icons (breeze icon theme). All icons are correctly displayed in Papirus and Adwaita icon themes.

**Comment by xfgusta** [comment]
> In Kubuntu 22.04 (Wike installed via flatpak), I can see the printer icon and new tab icon, but not some other icons (breeze icon theme). All icons are correctly displayed in Papirus and Adwaita icon themes.

Same here.

**Comment by spoorun** [comment]
> 1. Which version of Wike are you using?
2.0.1
> 
>     2. How did you install Wike?
via Flatpak
> 
>     3. Which operating system?
Manjaro Linux with KDE 5.27.4 running with Wayland

Apologies for not posting originally (I'd figured this was a problem with KDE compatibility).

**Comment by spoorun** [comment]
> ![image](https://user-images.githubusercontent.com/3063132/234993546-64c4904f-3e5f-489d-9616-43f568c14561.png)
> 
> ![image](https://user-images.githubusercontent.com/3063132/234993905-86672824-a06a-4c2a-882c-64468da3f7bc.png)
> 
> In Kubuntu 22.04 (Wike installed via flatpak), I can see the printer icon and new tab icon, but not some other icons (breeze icon theme). All icons are correctly displayed in Papirus and Adwaita icon themes.

In Manjaro KDE (Breeze icon theme) I'm missing the sidebar icon, new tab icon, and printer icon

**Comment by hugolabe** [comment]
39b8ec2b64a30cecc4a37fa5562e40db1b6a49d7

I've included most of the action icons as gresources (except the most common ones). This should fix the issue of missing icons  when using themes that don't include some of them.
