### ISSUE TITLE
open preview on touchscreen

### ISSUE THREAD

**Issue by camelCaseNick** [hugolabe/Wike#137]
Currently, the article previews are displayed on hovering over a link. 

Would it be a good idea that with the preview settings active, clicking on a touchscreen (i.e. with a pointer device without a hover option) would open the preview instead of directly going to the article?

**Comment by hugolabe** [comment]
From a technical point of view it would be complicated since popups are not a feature of the application, but of the Wikipedia website itself.

But, above all, it doesn't seem like a good idea to me. This is not the behavior a user expects when clicking a link.

**Comment by camelCaseNick** [comment]
> From a technical point of view it would be complicated since popups are not a feature of the application, but of the Wikipedia website itself.

I know. I'd try to implement it anyway, if you'd accept it.
> But, above all, it doesn't seem like a good idea to me. This is not the behavior a user expects when clicking a link.
It is exactly what I expected from Wike when I first used it with a touchscreen. (Not sure why, because I could have known better.) It is what the Wikipedia Android app does, after all – it opens a popup (more like a flap style view from below, but serves the same purpose) and that has a “read more” button.

**Comment by camelCaseNick** [comment]
![grafik](https://user-images.githubusercontent.com/2989008/236285801-74a2f925-6491-47de-aa6c-36a57e2fc0e7.png)

As I am used to the Android app, this is how I expect a link to behave. The mobile web version does not have this feature.

**Comment by camelCaseNick** [comment]
Would you accept it, if it was optional?

**Comment by hugolabe** [comment]
Thanks for the proposal @camelCaseNick 

However, one of my priorities is to keep the application as simple as possible and that happens by not loading it with options that I consider unnecessary. In this case it is a feature that frankly I do not like and I prefer not to include it.

I'm sorry.
