### ISSUE TITLE
Snap package ready and working

### ISSUE THREAD

**Issue by soumyaDghosh** [hugolabe/Wike#143]
Hi, you app is ready as a snap package and it's working perfectly. Would you like to publicise this?

**Comment by hugolabe** [comment]
Yes @soumyaDghosh 
I include it in the table of installation methods.
What are the link to the snap and the name/contact link of the maintainer?

**Comment by hugolabe** [comment]
I've updated the README to add Snap to the installation methods. 4eec4bc45009147c6948c5c2894955946380aed6

> Would you like to have this snap under your name in the store?

It doesn't seem necessary to me, since Flatpak is the only official package.
