### ISSUE TITLE
Ability to pin tabs

### ISSUE THREAD

**Issue by rene-coty** [hugolabe/Wike#145]
Something similar to epiphany, or any web browser. It would allow to save pages / reopen them quickly after the app is closed

**Comment by hugolabe** [comment]
The problem I see is how to identify the pinned tabs, since they only show an icon (in the case of a browser, each web page has a different favicon).

It may be a better option to add the possibility of restoring the tabs that were open when closing the app, as proposed in issue #100

**Comment by hugolabe** [comment]
I close it because in version 2.1 the option to restore open tabs has been added.

It is not the same as pinning tabs, but, as I said before, this would not be very practical due to the impossibility of distinguishing one pinned tab from another.
