### ISSUE TITLE
Remove filesystem access from the permission of the Flatpak sandbox

### ISSUE THREAD

**Issue by TitouanReal** [hugolabe/Wike#147]
Wike uses the permission '--filesystem=home', giving it access to any file in the home directory of the user. This should not be the case for what this application does, because it doesn't theoretically need a read/write access to the entire home directory.

If some sort of filesystem access is needed by the app, it would be nice to limit this access to the strict necessary, and to try to completely remove this permission in the future.

I couldn't figure out where this access is needed in the code unfortunately. Is it needed by the "Print" feature in some way? Maybe I am completely wrong on this one.

Thanks for considering the issue.

**Comment by camelCaseNick** [comment]
This would have been fixed by #129 and com.github.hugolabe.Wike#8.

However, WebKit assumes to have access to the Freedesktop.org user directories' downloads folder and crashes otherwise. Furthermore, WebKit does not simply spawn a file dialogue outside the flatpak's sandbox through a portal, and thus displays the selected file's location as mounted inside the sandbox under `/run`.

For those issues, there is an upstream bug: https://bugs.webkit.org/show_bug.cgi?id=192748

**Comment by TitouanReal** [comment]
I am sorry, I searched through the issues but I think I went over the closed ones too fast.

However keeping an issue open regarding this seems reasonable to me, because just fixing the webkit issue upstream will not fix the actual problem referenced here. It will only allow a fix that will need to be done eventually.

**Comment by pedropaulosuzuki** [comment]
> I am sorry, I searched through the issues but I think I went over the closed ones too fast.
> 
> However keeping an issue open regarding this seems reasonable to me, because just fixing the webkit issue upstream will not fix the actual problem referenced here. It will only allow a fix that will need to be done eventually.

[Webkit seems to have changed the print workflow](https://github.com/WebKit/WebKit/pull/26765). Maybe we can take another look at this now.

**Comment by hugolabe** [comment]
> [Webkit seems to have changed the print workflow](https://github.com/WebKit/WebKit/pull/26765). Maybe we can take another look at this now.

Thanks for letting me know. I'll check it again.

**Comment by hugolabe** [comment]
Done ace604e8dffef302c03a92fa197f1e73c5b766f7
