### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by bertob** [hugolabe/Wike#151]
For low connectivity cases it'd be cool to be able to download an archive with the most important articles to use offline. Perhaps articles that were downloaded once could also be cached for the future, to avoid additional data use.

For the fully offline case it'd be great if archives could be imported/exported as a file, to enable sharing them via USB keys and the like.

[This app](https://flathub.org/apps/com.github.birros.WebArchives) does something in this direction, but seems to be unmaintained.

**Comment by hugolabe** [comment]
Sorry for the delay @bertob 

This topic has been discussed other times. In these conversations I explain why I don't consider it: #15 #104

> [This app](https://flathub.org/apps/com.github.birros.WebArchives) does something in this direction, but seems to be unmaintained.

From what I have seen, this application works the same as [Kiwix](https://flathub.org/es/apps/org.kiwix.desktop), reading ZIM files.
