### ISSUE TITLE
Feature idea: Keyboard driven way to follow hyperlinks

### ISSUE THREAD

**Issue by J-Kappes** [hugolabe/Wike#152]
- I imagine a keyboard shortcut to start a mode similar to `Search`, possibly with a similar search bar popping in
  - Perhaps `ctrl + o` or `ctrl + y` for "f<ins>o</ins>llow / <ins>o</ins>pen h<ins>y</ins>perlink"
  - This "search bar" would not contain up or down arrows to click because the user could instead just click the link itself. This could help differentiate this bar from the real search bar.
- As the user types, only hyperlinks are searched incrementally and highlighted, perhaps in the same way as regular search
- Each hyperlink is a single result regardless of whether it contains multiple matches 
- pressing `tab`/`shift + tab`  focuses the next/previous match
- pressing `return` opens the link in the current tab
- pressing `shift + return` opens the link in a new tab and focuses it while closing the "follow link" mode in the origin tab
- pressing `ctrl + shift + return` opens the link in a new tab and takes no further action

Open question:
- Would we want to highlight each matching hyperlink in its entirety in addition to the matching part? This could get complicated with 2 kinds of highlight per match with different colors for the currently focused match. One could change the color of the link text or use frames, though the latter poses a problem with links spanning multiple lines

**Comment by hugolabe** [comment]
Frankly, I don't see the point of searching through the links. And it would not be something easy to implement. Text search is built into WebKit, but this would have to be implemented manually.

**Comment by J-Kappes** [comment]
> Frankly, I don't see the point of searching through the links

Just a quick way to reach any link by keyboard, even if it's in the middle of a page with 100+ links. Currently, you'd have to tab through it all.

**Comment by hugolabe** [comment]
The fact is that the article view is an instance of WebKit, which manages scrolling, text searches, etc. If this were supported by the WebKit API it would make sense to include it, but implementing it manually is not something I can easily do.

And it's not a feature that I find very useful either...

Sorry.
