### ISSUE TITLE
Support multiple tabs

### ISSUE THREAD

**Issue by raluvy95** [hugolabe/Wike#16]
This software is really cool, but it would be good if you add multiple tabs.

**Comment by hugolabe** [comment]
At the beginning of Wike's development I did some testing with tabs, but it made things more complicated and I wanted to keep the application as simple and light as possible.

I do not rule it out for the future, but at this moment my priority is to gradually improve the application while keeping it simple.

**Comment by tpurde** [comment]
I think this would help the usability of Wike a lot. Especially with something like grouped tabs, or something like Sidebery for Firefox.

**Comment by nicocarbone** [comment]
I understand that it is a complex problem to tackle. My use case would benefit from multiple tabs as I usually queue multiple articles while reading one. Bookmarks help, but in the browser I use tabs a lot.

Maybe an option to open the link in a new window will be easier to implement and help a bit in this case?

**Comment by hugolabe** [comment]
> Bookmarks help, but in the browser I use tabs a lot.

Yes, I use bookmarks to save what I want to read later and delete them when exit, but I understand that they do not totally replace tabs.

> Maybe an option to open the link in a new window will be easier to implement and help a bit in this case?

The problem is that Wike is not designed to run multiple instances and there would be conflicts between them.

**Comment by hugolabe** [comment]
Tabs view now in master.
Soon in a new release...
![wike-tabs](https://user-images.githubusercontent.com/18441950/135711452-347e7f1d-d7fa-43a7-a35b-0d9f46b9564f.png)

**Comment by apandada1** [comment]
How do I open a new tab?

**Comment by hugolabe** [comment]
> How do I open a new tab?

With the New Tab button (left to the Search Button) or by clicking on a link with the middle mouse button, in the same way as in a browser. You can also use the keyboard shortcut <kbd>Ctrl</kbd> + <kbd>N</kbd>
