### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by julianfairfax** [hugolabe/Wike#164]
It would be nice if Wike supported editing pages, with and or without an account, or, otherwise, if it supported opening a link in a browser that would directly bring you to the editing page for the page or section requested.

**Comment by hugolabe** [comment]
Editing articles is outside the scope of Wike, which only aims to provide quick and easy access to Wikipedia content.

In the main menu there is an option to open the article in the browser. This takes you to the Wikipedia page and there you just have to press Edit at the header of the article to enter editing mode.
