### ISSUE TITLE
There is no ability to reload the page

### ISSUE THREAD

**Issue by 73** [hugolabe/Wike#17]
How do I move away form this page?

![image](https://user-images.githubusercontent.com/529346/120984113-9edaa980-c77a-11eb-830e-099ab83ff4ae.png)

**Comment by apandada1** [comment]
Close, check your internet connection (check if you can open Wikipedia from
Browser) and reopen Wike.

**Comment by 73** [comment]
Thank you for the fast response. The connection was not ready when I opened Wike. However, that is not what I wanted to report here.

When the connection was back up I had to *reopen* Wike (like you said). There was no possibility to click on any button to "try again" (see screenshot). I am reporting that the user needs to *reopen* and the app does not say so. 
I see two options here:
1. Make "try again" clickable, so it reloads the page
2. Make the statement clear to *reopen* Wike

I hope that made it more clear.

**Comment by hugolabe** [comment]
It's not necessary to exit the app. Once the connection is reestablished, you can perform a new search or go to another page.

But I think it's a good idea that there is an option on the error page to try again.

**Comment by 73** [comment]
> Once the connection is reestablished, you can perform a new search or go to another page.

Or simply put that in the placeholder. However, at least I expected to have a button or a link on "try again".

**Comment by hugolabe** [comment]
Added a "Try Again" button to the connection error page.

![Wike-try-again](https://user-images.githubusercontent.com/18441950/122552435-987be580-d036-11eb-827a-88fa50ffb1af.png)
