### ISSUE TITLE
Font type and text size

### ISSUE THREAD

**Issue by sslaia** [hugolabe/Wike#173]
Hi, thank you for this app. I quite like it. Is it possible to change the font (in the preferences) and a button to increase/decrease the text size?

The reason: 1) on my monitor the text are a bit too small and 2) the text could be reading-friendlier if with selectable fonts.

Thanks.

Edit (22/12/2023, 18:35): The message above is related to the Wike installed on Debian 12. 

I tried it on Ubuntu and it has the option to change the font type and size. 

However on Ubuntu there is no option to change the language, which exists in Wike on the Debian version. The Preferences has only one tab on Ubuntu (consists only Behaviour and Privacy options) while on Debian it has three tabs (General, Privacy, Languages)

**Comment by hugolabe** [comment]
From what you say, I assume that the version available in Debian is quite old (prior to version 2)

Starting with version 2, the choice of languages is not in preferences but rather has its own window that you can access through a button in the search settings popover.

![wike-languages](https://github.com/hugolabe/Wike/assets/18441950/136578e1-9638-4ec7-93ac-0f435c368bcb)

**Comment by sslaia** [comment]
Thanks. My mistake.
