### ISSUE TITLE
Missing wikipedia languages

### ISSUE THREAD

**Issue by ChildishGiant** [hugolabe/Wike#175]
In most every article very few languages are offered compared on web.

![image](https://github.com/hugolabe/Wike/assets/13716824/c03fd8be-bffc-4973-b66a-9ede0ef1167b)
![image](https://github.com/hugolabe/Wike/assets/13716824/9f0af976-710d-41da-8f20-6ad3b1865a39)

**Comment by hugolabe** [comment]
Hi @ChildishGiant 

This list only shows the languages that you have chosen to use.

[wike-languages.webm](https://github.com/hugolabe/Wike/assets/18441950/f099ed2e-9fe1-48bb-9ce5-44abfb99df77)

**Comment by camelCaseNick** [comment]
The official Wikipedia app also has the option to select a set of languages, but also displays the complete list of available languages regardless. So, this could be considered a feature request to follow this:

![image](https://github.com/hugolabe/Wike/assets/2989008/e0bd8c0c-2837-4b0c-b4f4-173d4900c877)

**Comment by hugolabe** [comment]
> The official Wikipedia app also has the option to select a set of languages, but also displays the complete list of available languages regardless.

I know, although I don't know if it's very useful to show languages you don't speak.

I'll think about it while I'm making some changes to the UI that affect the sidebar.

**Comment by hugolabe** [comment]
In version 3, which I just published, I have added an option to display all languages or only those selected by the user.
![wike-langlinks](https://github.com/hugolabe/Wike/assets/18441950/c8f6121c-682a-4234-a161-6aeae01c565f)
