### ISSUE TITLE
Wike lacks article or citation preview on hover.

### ISSUE THREAD

**Issue by tpurde** [hugolabe/Wike#18]
Wikipedia has this awesome feature that shows a preview of an article when you hover over a hyperlink or a citation. I think this would be beneficial for the ease of use of Wike.

Example:
![Screenshot_20210613_164501](https://user-images.githubusercontent.com/62025836/121809793-eecbdb80-cc66-11eb-8a05-5345245e9bd3.png)

**Comment by hugolabe** [comment]
The truth is that I have intentionally removed them as I wanted to keep the view of the articles as clean as possible and I find these popups a bit intrusive.

**Comment by tpurde** [comment]
Is there a way this could be added as a setting? In my honest opinion, they are crucial for complex topics, even like history or Greek mythology.

**Comment by hugolabe** [comment]
Perhaps an option could be added in preferences. I'll take a look when I have time.

**Comment by tpurde** [comment]
Alright, thanks for checking the issue

**Comment by hugolabe** [comment]
Version 1.5.0 now includes an option in preferences to enable preview popups.

![Wike-preview-popups](https://user-images.githubusercontent.com/18441950/122552603-cf51fb80-d036-11eb-8e9d-087fc7f3fed0.png)

**Comment by rafaelmardojai** [comment]
> Version 1.5.0 now includes an option in preferences to enable preview popups.

Shouldn't it be in **Behavior** rather than  **Appearance** ?

**Comment by hugolabe** [comment]
You think?
It seemed to me that it has more to do with the appearance than with the behavior, since it affects how the articles are displayed...

Or maybe the **Appearance** group should be called **Article View**...

**Comment by rafaelmardojai** [comment]
To me it's about how the article view behaves rather than it's appearance. So yeah, **Article View** makes more sense if you want them grouped.
