### ISSUE TITLE
Wike error at start

### ISSUE THREAD

**Issue by dacorsa** [hugolabe/Wike#180]
Hi all,
can you help me?

$ /usr/local/bin/wike 
Traceback (most recent call last):
  File "/usr/local/bin/wike", line 33, in <module>
    from wike import application
  File "/usr/local/share/wike/wike/application.py", line 16, in <module>
    from wike.prefs import PrefsDialog
  File "/usr/local/share/wike/wike/prefs.py", line 15, in <module>
    class PrefsDialog(Adw.PreferencesDialog):
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'PreferencesDialog'. Did you mean: 'PreferencesWindow'?

Thanks, best regards.

**Comment by hugolabe** [comment]
@camelCaseNick  is right.

I understand that you have installed manually from source code. In recent commits several dialogs have been migrated to the new adaptive dialogs that require libadwaita 1.5, but this has not yet been published in the stable version.

**Comment by dacorsa** [comment]
But why, if ubuntu in last version 23.10 has libawaita 1.4, why use 1.5? i can compile the 1.6 alpha but how can i run Wike with libawaita 1.6 alpha in /usr/local/include/libawaita-1???

thanks

**Comment by hugolabe** [comment]
> But why, if ubuntu in last version 23.10 has libawaita 1.4, why use 1.5?

1.5 is the latest stable version of libadwaita and provides new adaptative dialogs that most GNOME applications are migrating to.

> i can compile the 1.6 alpha but how can i run Wike with libawaita 1.6 alpha in /usr/local/include/libawaita-1???

I can't help you with that. I only work with the flatpak version.

**Comment by dacorsa** [comment]
and for compile a flatpak version? thanks

**Comment by hugolabe** [comment]
If you only want to install the latest stable version (3.0.1), it is best to do it from Flathub:

https://flathub.org/es/apps/com.github.hugolabe.Wike

If what you want is to install from the last commit you can download an automatically generated flatpak package from the Actions section of GitHub:

https://github.com/hugolabe/Wike/actions/runs/8491362755

![wike-flatpak-download](https://github.com/hugolabe/Wike/assets/18441950/88f5156f-4a98-4aac-b948-9a10b3027f46)

And then install it using the command:
`flatpak install com.github.hugolabe.Wike.flatpak`

Please note that these are unpublished builds and may contain errors.
