### ISSUE TITLE
Ctrl+C to copy not working

### ISSUE THREAD

**Issue by cheywood** [hugolabe/Wike#188]
Hello, congratulations and thanks for Wike! :pray:

I don't appear to be able to use Ctrl-C to copy article content here. Right-click and copy works fine. I'm running the v3.0.1 Flatpak so I presume that should include the #126 change?

**Comment by hugolabe** [comment]
Thanks @cheywood !

The problem is caused by changes made in version 3. Fixed in commit f38b01cf54a67c26dacdbf28a36e72538dd1addd

**Comment by cheywood** [comment]
Thanks Hugo!
