### ISSUE TITLE
Browser Extension to Switch to Wike

### ISSUE THREAD

**Issue by petres** [hugolabe/Wike#189]
Are there some browser extensions for firefox, chrome, ... which allow opening a wike with the content of the currently browsed wikipedia page?

**Comment by hugolabe** [comment]
As far as I know there is no extension.

In theory it would be possible to do this, since Wike supports passing a Wikipedia URL as a parameter on the command line. Personally, I have no knowledge of developing extensions nor much interest in doing so.
