### ISSUE TITLE
Add option to login with account

### ISSUE THREAD

**Issue by TheEvilSkeleton** [hugolabe/Wike#19]

**Comment by apandada1** [comment]
Why would you want to sign in? Do you want to edit within Wike?

Let's keep it a simple and fast Wikipedia reader instead. Otherwise it may become bloated and resource hungry like modern browsers.

**Comment by TheEvilSkeleton** [comment]
Not just edit, but I want to be able to view my history as well.

Fair enough. Should we close this issue?

**Comment by apandada1** [comment]
You can view your history in Menu --> Recent Articles icon

![image](https://user-images.githubusercontent.com/3063132/121889219-98c66900-cd36-11eb-9843-4282431656e8.png)

**Comment by TheEvilSkeleton** [comment]
Thank you!
