### ISSUE TITLE
[Suggestion] Prefix for Live Searches

### ISSUE THREAD

**Issue by LSeelig** [hugolabe/Wike#190]
Currently, if live searches are enabled, any search from the GNOME desktop has to be sent to Wikipedia. What if, just like how prefixes are used to search in different languages, a prefix could be used for live searches?

**Comment by hugolabe** [comment]
Frankly, it seems to me to complicate something that should be simple and would be difficult for most users to discover.

Wike already has a way in which it does not send desktop searches to Wikipedia and you can always do searches from the app to get suggestions.

**Comment by LSeelig** [comment]
I respect that. And I suppose a system-wide implementation, or at least an extension, would be better than having each app implement it.
I based the suggestion on the Extension Search Provider GNOME Extension.
![image](https://github.com/user-attachments/assets/49073252-f0b5-47fc-b12e-e96d7c4b54e0)
