### ISSUE TITLE
Wiktionary support?

### ISSUE THREAD

**Issue by soumyaDghosh** [hugolabe/Wike#193]
Absolutely love this app! But would appreciate a Wiktionary mode. That way you will make arguably the best dictionary/thesaurus app, and I don't have to use GoldenDict anymore!

Cross posting from my snap repo.

https://github.com/soumyaDghosh/wike-snap/issues/1

**Comment by hugolabe** [comment]
This proposal has already been raised other times: #31 #134 #142

I think different services have different needs when it comes to app design and I prefer to keep Wike simple and single-purpose oriented.
