### ISSUE TITLE
Cantarell

### ISSUE THREAD

**Issue by 73** [hugolabe/Wike#2]
Nice idea and good feature set!
Wike 1.1.0 from Flathub
I would like a even more native look. That would mean to have Cantarell as font. I see three options here:

1. Hardcode: Make Cantarell the default font
2. Use the default document font: `gsettings get org.gnome.desktop.interface document-font-name`
3. Allow custom css.

**Comment by hugolabe** [comment]
The articles view uses the mobile version of Wikipedia customized with CSS. I prefer to modify the Wikipedia design as little as possible to keep it consistent.

On the other hand, I find Cantarell an excellent font for the user interface, but not so great for displaying large amounts of text ...

**Comment by 73** [comment]
I don't argue readability, I argue consistency. ;)
[Cantarell is the default document font in GNOME](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/blob/master/schemas/org.gnome.desktop.interface.gschema.xml.in#L159).

**Comment by hugolabe** [comment]
Yes, but it is also important to maintain the consistency of the Wikipedia layout.

And readability is essential! ;-)

**Comment by 73** [comment]
I was under the impression that your app should embed wikipedia more native looking into the desktop. If you just want a standalone browser app, [there is an easier way](https://help.gnome.org/users/epiphany/stable/browse-webapps.html.en). Feel free to close this issue as out of scope.

**Comment by hugolabe** [comment]
Thanks for your suggestions.
I'm leaving it open for now and will consider adding the option to choose the font in the future.

**Comment by hugolabe** [comment]
Added an option in preferences to choose a custom font, so I think it can be closed.

**Comment by hellpe** [comment]
For further reference about Wikipedia's choice of fonts: https://phabricator.wikimedia.org/T244425
