### ISSUE TITLE
changing search language with filled in search term does show new suggestions

### ISSUE THREAD

**Issue by camelCaseNick** [hugolabe/Wike#21]
When
1. opening article search field
2. filling in a complete search term in a language different from the currently selected
3. selecting the correct language

the language switch does either not repopulate or does not open the suggestion popup. Looking into the source code, I suspect it is the former.

Therefore, it is required to make dummy key presses like entering a space to re-trigger the suggestion popup.

**Comment by hugolabe** [comment]
I think that once the suggestions popover is closed (when opening the search settings) it's logical that you have to type again to make it appear. The opposite does not seem very consistent to me.

It would also overlap with the language change notification.

**Comment by camelCaseNick** [comment]
If it is my fault, that I forget which language is set. Then it would make sense to clear the search field on a new language selection then?

**Comment by hugolabe** [comment]
I do not know. I don't think it's bad that the search term is kept.

Tip: Hovering over the gear icon displays the active language.
