### ISSUE TITLE
Use proper dice icon for "random article" primary menu button

### ISSUE THREAD

**Issue by Vanadiae** [hugolabe/Wike#25]
A new icon can be requested for the Icon Development Kit by opening an issue at https://gitlab.gnome.org/Teams/Design/icon-development-kit/-/issues

**Comment by hugolabe** [comment]
I don't find the current icon a bad fit for what it represents. I understand that at first it may not be clear what this button does, but it can be solved by adding tooltips to this and other buttons.

**Comment by hugolabe** [comment]
I think the dice icon is a good option as it is now available.
Commited.

**Comment by apandada1** [comment]
Upstream icon changed because it resembled an iPod/phone screen. https://gitlab.gnome.org/Teams/Design/icon-development-kit/-/issues/40

**Comment by hugolabe** [comment]
What do you think is the best option?
![wike-dice1](https://user-images.githubusercontent.com/18441950/131711797-81de50a4-903f-41d4-afb8-fa90f5b634af.png)
![wike-dice2](https://user-images.githubusercontent.com/18441950/131711820-082a8bc2-65d7-4d98-9c91-050e860ed062.png)

**Comment by apandada1** [comment]
I would prefer the second one above the first one. I suggested showing three sides of the die in upstream, but 3D view seems to be against the GNOME guidelines.

What do you think, @Vanadiae ?

**Comment by Vanadiae** [comment]
Well I _can see_ how you could think the first one looks like a mobile phone , though I don't quite see it like that at first. To me it does look like a dice as the front dice side isn't fully filled like the bottom part, which creates sort of a 3D effect. But anyway both look like a dice so no strong opinion here, both will work fine.

**Comment by hugolabe** [comment]
I agree with Vanadiae that they both look like a dice and I don't think they are misleading. From an aesthetic point of view I like the first one better. The second one looks very dark and a bit out of place next to the other icons.

I think we can leave the first one that is already in master.

**Comment by apandada1** [comment]
> I think we can leave the first one that is already in master.

Sure.
