### ISSUE TITLE
Implement type-to-search to search new page

### ISSUE THREAD

**Issue by Vanadiae** [hugolabe/Wike#28]
Since the wikipedia pages shown by Wike will almost never have a text input area, it makes sense to provide a type-to-search feature like all GNOME apps. Searching in a page is less often useful than opening a new page I'd say (and it has Ctrl+F even then), so searching for a new page using the headerbar's entry is a reasonable behavior when typing text in the app.

**Comment by hugolabe** [comment]
It seems to me an interesting option.

Only one keystroke would really be gained as there are keyboard shortcuts to trigger article search, but I'll do some testing when I have time.

**Comment by janxkoci** [comment]
> like all GNOME apps

Well, there are some exceptions, most notably **GNOME Web (Epiphany)**, which is what most people use to read Wikipedia (who don't know this app).

At least when talking about GNOME apps - I think this can be enabled in Firefox.
