### ISSUE TITLE
Feature Request - Wikitionary

### ISSUE THREAD

**Issue by VarLad** [hugolabe/Wike#31]
Is it possible to extend Wikitionary in this application?
If not, is it feasible to make a new wikitionary application from this?

**Comment by hugolabe** [comment]
Including it in the application does not seem like a good idea to me. I prefer to keep Wike as a simple app that does one thing and does it well.

On the other hand, there are already dictionary applications for GNOME, even some based on Wiktionary:
https://flathub.org/apps/details/com.github.johnfactotum.QuickLookup
