### ISSUE TITLE
Feature Request: Detect user's language for use in language of wikipedia pages by default

### ISSUE THREAD

**Issue by HoboPrimate** [hugolabe/Wike#35]
Would be a nice internationalization win if Wike detected the user's language and picked it for the default language to show wikipedia pages in.

If different than EN, then preselect EN as one of the languages to filter, so it would be easy to switch to it.

**Comment by hugolabe** [comment]
I'm not sure it's a good idea to preselect the search language.

Many of the local Wikipedias have very little content and their users will surely turn to the English version or other languages.

Another problem is that the language codes used by Wikipedia are not the same as Linux ones.

**Comment by HoboPrimate** [comment]
Ah yes, perhaps you're right, I was guiding myself on the portuguese wikipedia which is large, but that may not be the case for a lot of other languages.

**Comment by hugolabe** [comment]
Yes. I think it's better to leave to the user the choice of which languages ​​he wants to use.
