### ISSUE TITLE
Better icon for language change (in headerbar)

### ISSUE THREAD

**Issue by HoboPrimate** [hugolabe/Wike#36]
The flag icon is sometimes used on the web to signify "report a post/flag a comment". Myself it took me a while to find where to change the language.

A few examples of language icons with better metaphors:

[duckduckgo image search for "language icon"](https://duckduckgo.com/?q=language+icon&t=ffab&iar=images&iax=images&ia=images)

**Comment by apandada1** [comment]
See https://github.com/hugolabe/Wike/issues/27.

Sure, an icon like ![image](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.wqBs_huQ4TJfu2qfi_b3tQHaHa%26pid%3DApi&f=1) would be better, but the popular icon themes (e.g. Adwaita, Papirus) do not have such an icon, and it might look out of place.

**Comment by hugolabe** [comment]
This has been covered before.

Perhaps the best thing would be something similar to what @apandada1 says, although more simplified.

![Translation_icon](https://user-images.githubusercontent.com/18441950/131373596-1aa28d80-9af4-4f75-94ab-d3a578bfc95e.png)

However, currently it does not exist among the Icon Development Kit.

**Comment by hugolabe** [comment]
https://gitlab.gnome.org/Teams/Design/icon-development-kit/-/issues/39

**Comment by hugolabe** [comment]
Available (thanks @jimmac) and commited
![wike-langlinks](https://user-images.githubusercontent.com/18441950/131491650-4e98bfee-dba2-48d1-9856-509165c75d8a.png)

**Comment by Vanadiae** [comment]
Thanks for changing the icon @hugolabe ! :)
