### ISSUE TITLE
other language by default

### ISSUE THREAD

**Issue by sunnlife1978** [hugolabe/Wike#37]
HI,
Thank you for this useful software.
I would like to search for articles in French by default. I have checked "fr" in the preferences and unchecked "en" for English but inevitably when I search for an article, I get the English article as a response.
What should I do to solve this?
Thanks
Alex

**Comment by hugolabe** [comment]
In the search input you have to press the gear icon to access the popover of the search preferences.
![default-language](https://user-images.githubusercontent.com/18441950/131375923-c3ff5d9a-3a3d-438e-935d-677984917cbe.png)

The language you select there is set as the default language for searches.

**Comment by sunnlife1978** [comment]
Great !!!!
Thanks !!!!
