### ISSUE TITLE
Sepia mode

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#39]
In addition to the very nice dark mode, it would be nice to have the option of a sepia mode.

Font color: `#5b4636`
Background color: `#f4ecd8`

**Comment by hugolabe** [comment]
It could be interesting to have a Sepia mode, although it would surely not be as simple as changing two colors if you want to get a good result. It would even be nice to adapt the UI colors.

**Comment by apandada1** [comment]
Foliate ebook reader has a nice sepia mode. It only changes the font and the background colors, but it looks quite nice.
![image](https://user-images.githubusercontent.com/3063132/132041666-903ff77e-ab68-4beb-8a24-6b7332b4d589.png)

**Comment by hugolabe** [comment]
Yes, but there is only text there. In a Wikipedia article there are many other elements that might be a bit out of place ... or not. I'll be doing some tests when I can.

**Comment by vanillajonathan** [comment]
@apandada1 Yeah, also Mozilla Firefox and Microsoft Edge.

**Comment by vanillajonathan** [comment]
@hugolabe Version 1.6.0 seems to include a sepia mode!
Nice! 

Can you change the colors to font color to `#5b4636` and the background color to `#f4ecd8`?
These are the colors used by Firefox and would lead to a better sepia experience that is more comfortable.

**Comment by apandada1** [comment]
How about adding a custom mode where the user can put an hexadecimal color code?

**Comment by hugolabe** [comment]
> It's not only a matter of taste

Not only, but there is a part of designer's choice as there is not a standard. Each app uses a different color scheme.
