### ISSUE TITLE
Add a match case option to find on page

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#41]
When finding text on the page (<kbd>Ctrl</kbd>+<kbd>F</kbd>) there could be an option to match case (toggle case sensitive search).

**Comment by hugolabe** [comment]
I really think these options don't add much and are rarely used. In fact, most GNOME applications and browsers like Chrome, Brave, Web ... do not include them in their search boxes (Firefox does).

I prefer to keep the search bar simpler. At some point I would like to make the UI adaptable to mobile screens and then there would not be so much space.

**Comment by vanillajonathan** [comment]
In gedit you have the match case option, but it is a bit hidden, first you have to press <kbd>Ctrl</kbd>+<kbd>F</kbd> then you have to click on the magnifying glass icon and a menu presents itself with a checkbox for match case.

The adaptable UI for mobile screens sounds great!
This match case option could be one that is only visible on larger screens but gets hidden on smaller screens.

**Comment by hugolabe** [comment]
I know that there are applications that include these options, but the point is that I don't want to fill Wike with features that in my opinion are neither necessary nor very useful.
