### ISSUE TITLE
Add a match diacritics option to find on page

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#42]
When finding text on the page (<kbd>Ctrl</kbd>+<kbd>F</kbd>) there could be an toggle option to match diacritics.

Currently Wike always matches diacritics so if you search for "Ånger" it also finds "Anger".

**Comment by hugolabe** [comment]
Same as #41

**Comment by vanillajonathan** [comment]
No, this issue is not the same. This issue is about diacritics, that issue is about case sensitivity.

In Mozilla Firefox when you press <kbd>Ctrl</kbd>+<kbd>F</kbd> you have two checkboxes, one for "Match Case" and one for "Match Diacritics".

**Comment by hugolabe** [comment]
I did not mean that it is the same issue, but that the answer is the same since they are functionalities that go in the same direction.
