### ISSUE TITLE
Add some more keyboard shortcuts

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#43]
<kbd>F10</kbd> to open the menu.
<kbd>F11</kbd> to toggle fullscreen.
<kbd>Ctrl</kbd>+<kbd>?</kbd> show keyboard shortcuts.
<kbd>Ctrl</kbd>+<kbd>L</kbd> (in addition to <kbd>Ctrl</kbd>+<kbd>K</kbd>) for article search. Epiphany, Chrome, Edge, Firefox all support both <kbd>Ctrl</kbd>+<kbd>K</kbd> and <kbd>Ctrl</kbd>+<kbd>L</kbd>.

**Comment by hugolabe** [comment]
<kbd>F10</kbd> Yes.
<kbd>F11</kbd> Currently Wike does not have a full screen mode.
<kbd>Ctrl</kbd>+<kbd>?</kbd> Wike use <kbd>Ctrl</kbd>+<kbd>F1</kbd> but most GNOME applications use the one you say so it seems like a good idea to change it.
<kbd>Ctrl</kbd>+<kbd>L</kbd> In browsers they have a different function: <kbd>Ctrl</kbd>+<kbd>K</kbd> to search and <kbd>Ctrl</kbd>+<kbd>L</kbd> to select the page URL. It seems more logical to use <kbd>Ctrl</kbd>+<kbd>K</kbd> to activate search input. In addition, Wike also uses <kbd>F2</kbd> as an alternative and having three shortcuts for the same seems exaggerated to me.

**Comment by vanillajonathan** [comment]
Consider adding a fullscreen mode, many applications such as Gedit, Eye of GNOME, Evince, Totem, Epiphany, Shotwell, etc support fullscreen mode with F11.

When you read an Wikipedia article you might want to read it in fullscreen for a distraction-free experience.

**Comment by hugolabe** [comment]
Yes, I have considered it at some point, but it's in the queue ;)

**Comment by hugolabe** [comment]
59349383fa3339d9f8f195b1406ce57c6d2cbd12

**Comment by vanillajonathan** [comment]
Hope to see a fullscreen feature in the future for distraction-free reading!
