### ISSUE TITLE
Sidebar for table of contents

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#44]
The table of contents can be rather tricky to navigate as well as difficult to get a overview of, especially the headers are nested in multiple levels.

I would propose to add a sidebar for the table of contents such as the one in [Evince](https://wiki.gnome.org/Apps/Evince).

https://linuxmasterclub.com/wp-content/uploads/2020/10/Evince.-Sidebar.-Content.png

This sidebar could be toggleable using <kbd>F1</kbd> (like Evince, Nautilus, gedit, etc).

**Comment by hugolabe** [comment]
This is duplicated #26
