### ISSUE TITLE
How can I make a wrapper like this for another site?

### ISSUE THREAD

**Issue by ghost** [hugolabe/Wike#47]
Is it difficult for a guy who doesn't know anything about coding? I'd like a wrapper for Notion.

**Comment by airon90** [comment]
This software is not a wrapper for Wikipedia. It uses [its API](https://github.com/hugolabe/Wike/blob/master/src/wikipedia.py#L26).

**Comment by hugolabe** [comment]
Also, GNOME Web itself allows you to create web applications from any page. Or other browsers like Brave, Chrome ...
