### ISSUE TITLE
GNOME Shell search provider

### ISSUE THREAD

**Issue by rafaelmardojai** [hugolabe/Wike#5]
Would be awesome to get Wikipedia results when you search on GNOME Shell.

**Comment by hugolabe** [comment]
It could be a nice feature.
I don't know how Shell search work, but I will try to research it.

**Comment by rafaelmardojai** [comment]
In Dialect we have an example using `python-dbus` for a nicer pythonic syntax:  https://github.com/gi-lom/dialect/tree/main/src/search_provider. If you want to do it directly with `Gio` there's an example in Lollypop: https://gitlab.gnome.org/World/lollypop/-/blob/master/search-provider/.

Basically you need to write a D-BUS Service that will be called when you search in GNOME.

I haven't seen the Wike code yet, but you can import modules from Wike in the service so you can reuse some search code. You also will need to add a command line option to open Wike with an specific Wikipedia article so you can open the results in the app.

**Comment by hugolabe** [comment]
Thanks!
I will take a look.

**Comment by hugolabe** [comment]
Already in revision at flathub.org Wike 1.5.0 with GNOME Shell search integration.

**Comment by rafaelmardojai** [comment]
Thanks! Works great.

Keep the good work!

**Comment by lionirdeadman** [comment]
Does this send all search queries into Wikipedia? I'd like to use this feature but that seems a bit scary from a privacy perspective. Maybe it could search previous search suggestions (stored locally) and/or bookmarks?

I totally understand if this is too much work. This is a great application and it's very much appreciated.

**Comment by hugolabe** [comment]
I think this feature loses a lot of its functionality if Wikipedia searches are disabled, but I understand the privacy concern.

Perhaps the best thing would be to add an option in preferences that is disabled by default. In that case the search could be done only in the historic and/or show a **Search for "term" in Wikipedia** entry in the results. It is something similar to what GNOME Web does.

Search can also be disabled in system settings, so I don't know if it's worth it ...

**Comment by rafaelmardojai** [comment]
The best privacy oriented approach is to go with the `Search for "term" in Wikipedia` thing by default, and add an option to show full Wikipedia results.

**Comment by hugolabe** [comment]
> The best privacy oriented approach is to go with the `Search for "term" in Wikipedia` thing by default, and add an option to show full Wikipedia results.

Yes. I agree.
