### ISSUE TITLE
Search in multiple languages

### ISSUE THREAD

**Issue by mskf1383** [hugolabe/Wike#51]
switching between languages are very boring. and somewhere (in live desktop search) is impossible.
It's better to can search in all selected languages.
Thanks!

**Comment by hugolabe** [comment]
Do you mean to search every time in all the selected languages? It doesn't seem viable to me. There is not a single Wikipedia with multiple languages ​​but many different Wikipedias, so they are separate searches. Besides the performance issues it might cause, what results should be displayed in the list of suggestions?

I do not find it difficult to change the active language, but you can also search in one language and easily open the article in the others using the `View article in other languages` popover:
![wike-langlinks](https://user-images.githubusercontent.com/18441950/132212937-38f14258-8cff-4447-b100-ae4dccdd16b3.png)

**Comment by mskf1383** [comment]
Correct
What about an option to set language in live desktop search?
for example:
`en: article name`
to search in English
and
`فا: نام مقاله`
to search in Persian.

**Comment by hugolabe** [comment]
32fd4645fd722364925f75a1fd939e50855974ca

Now desktop searches can be done in multiple languages. To do this, a hyphen followed by the Wikipedia language code must be used as a prefix (all codes can be seen in the language list).

Eg `-es` to search in Spanish

**Comment by mskf1383** [comment]
Nice 👍
I'm waiting for next release to test it!
