### ISSUE TITLE
No preview popup on devices where both touch and mouse input are present

### ISSUE THREAD

**Issue by CharoSW** [hugolabe/Wike#59]
On version 1.5.7 the preview popup doesn't seem to work, i seem to only get tooltips instead of the previews.  I noticed it on the flatpak version but also looked at the native fedora package and couldn't them there either

**Comment by CharoSW** [comment]
So that unfortunately didn't work but it did lead me to look into it a bit deeper.  The true problem seems to be the fact that I have an external touch screen and the preview popups dont like that.   If the touch screen is connected when I start Wike then I get just tooltips, if i disconnect the touchscreen and then start Wike the previews are there.   The behaviour makes some sense in the fact that touchscreens can't have a hover but unintentionally creates a hole when you have a device with both touch and mouse/pointer input.  I will change the bug title to reflect this new angle

**Comment by hugolabe** [comment]
I don't think I can do anything about that, since the rendering of the page is done by WebKit.

[Page Previews](https://www.mediawiki.org/wiki/Page_Previews) are a feature of Wikipedia itself. When they are deactivated in preferences, the only thing that Wike does is inject a css rule in the web view to hide those elements.

**Comment by aunetx** [comment]
I have this issue too, @hugolabe do you think it is worth it for me to open an issue for webkit?

**Comment by hugolabe** [comment]
First try if the same thing happens to you with GNOME Web, which also uses WebKit...

**Comment by aunetx** [comment]
Yeah it does happen too, but I still have not isolated the reason (i guess it's a bug with the mouseenter event)
