### ISSUE TITLE
Add "Open Link in Web Browser" to context menu

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#60]
Sometimes when reading an article, I would like to edit it.

It would be good with a "Open Link in Web Browser" entry in the context menu when right-clicking on a link.

**Comment by vanillajonathan** [comment]
Ah good point. Maybe this could be a useful addition anyway. Along with an entry for "Copy Link".

**Comment by hugolabe** [comment]
5881c0f8a8ecfcbc7161d28423e410e1d6f767a5
