### ISSUE TITLE
Change the default language of searches?

### ISSUE THREAD

**Issue by CavaleriOmar** [hugolabe/Wike#62]
Is there any way to change the default search language from English to other, without having to set it every time you open a tab?

**Comment by GeoffreyCoulaud** [comment]
I just stumbled on this question, thinking the search was limited to english. First of all, thanks for the clarification.  
Maybe the searchbar cog is not explicit enough, making the feature less discoverable ?

**Comment by hugolabe** [comment]
Yes. In version 2 the active language will be displayed in the search bar and access to search options will be more obvious.
