### ISSUE TITLE
Ability to download article as PDF

### ISSUE THREAD

**Issue by faelana** [hugolabe/Wike#64]
I purpose the ability to download an article as PDF, this is not hard to do, wikipedia alredy has this feature and adding it would be just the same process as "Open Wikipedia page in browser". Simple feature that would be very useful.

Screenshots/Examples:
![Screenshot from 2021-10-26 17-22-08](https://user-images.githubusercontent.com/46012160/138921066-d2ea28c6-81a6-4f33-93c3-385c1acd6a05.png)
`https://en.wikipedia.org/w/index.php?title=Special:DownloadAsPdf&page=Alexei_Navalny&action=show-download-screen
`
![Screenshot from 2021-10-26 17-27-37](https://user-images.githubusercontent.com/46012160/138921226-1565d329-2e88-4165-96de-81375a8f1d16.png)
![Screenshot from 2021-10-26 17-43-54](https://user-images.githubusercontent.com/46012160/138923806-e67b58ad-d04b-4010-a492-62f46e0a2444.png)
As i tested you can also download it directly without landing in the Download as PDF page with:

```
https://en.wikipedia.org/api/rest_v1/page/pdf/Patriot_Act
https://en.wikipedia.org/api/rest_v1/page/pdf/Name_Of_Article
```

**Comment by hugolabe** [comment]
In version 2 the option to print articles has been added. This also allows you to export them to PDF using the “Print to PDF” option.
