### ISSUE TITLE
Preferences windows doesn't stick to main window

### ISSUE THREAD

**Issue by octowaddle** [hugolabe/Wike#7]
Usually, these smaller pop-out windows (I don't know how to call them) like the preferences window should stick to the main parent window. Wike does this for the About window and the Keyboard Shortcuts window, but not for the preferences window.

**Comment by hugolabe** [comment]
I don't know why it happens. The prefs window is defined as modal and transient from the main window. I will try to find out.

**Comment by 73** [comment]
Just in case the problems are related: With me the preference window is not even opened. The app freezes completely.

**Comment by hugolabe** [comment]
@73 It has never happened to me.
Have you installed it as a flatpak?
Does it show any error message if you start it from command line?

**Comment by 73** [comment]
> Have you installed it as a flatpak?

Yes, latest version.

> Does it show any error message if you start it from command line?

No, it does not.

**Comment by hugolabe** [comment]
You could try to delete the application data folder, in case any file is damaged. The settings, favorites, history ... will be deleted and the folder will be created again when the application is started.

The folder is: `~/.var/app/com.github.hugolabe.Wike`

**Comment by 73** [comment]
Did `rm -fr  ~/.var/app/com.github.hugolabe.Wike`. Same result.

**Comment by 73** [comment]
- `--verbose` still does not give any error
- Every other button works as expected

**Comment by 73** [comment]
Yes I have. I am on Ubuntu 20.10.

**Comment by 73** [comment]
This is the full output in case you see something suspicious: 
```
🠶  flatpak run --verbose com.github.hugolabe.Wike
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2186214675
F: Allocated instance id 1557360748
F: Add defaults in dir /com/github/hugolabe/Wike/
F: Add locks in dir /com/github/hugolabe/Wike/
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/user/.config/pulse/client.conf': Error opening file /home/user/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 35 xdg-dbus-proxy --args=37'
F: Running 'bwrap --args 35 wike'
Gtk-Message: 17:43:18.965: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:43:19.126: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:43:19.127: Failed to load module "canberra-gtk-module"
^C
```

**Comment by hugolabe** [comment]
I don't see anything weird.
I use Ubuntu 20.04
I will try to test it in 20.10 when I have a while, although it should be independent of that ..

**Comment by 73** [comment]
Thanks.

**Comment by 73** [comment]
I tried my home machine (ubuntu 20.04) and it works.

**Comment by hugolabe** [comment]
Tested on Ubuntu 20.10 with a live image it works fine for me.

![wike-ubuntu-2010](https://user-images.githubusercontent.com/18441950/116807275-90bdbb80-ab32-11eb-9db3-9dac13dd21ee.jpg)
