### ISSUE TITLE
Feature request: possibility to open tabs in different windows

### ISSUE THREAD

**Issue by Camiropan** [hugolabe/Wike#72]
first of all, thanks for this nice app!

It would be very helpful if there would be a way to open tabs in different windows. Like the tabs in gnome-console or in tabview-demo in adwaita-demo
![Tabview_demo](https://user-images.githubusercontent.com/76531567/159474195-3de52c3b-b164-4d88-bc97-e33eeb5d1881.png)
.

**Comment by hugolabe** [comment]
Thank you!

Wike does not currently support multiple instances of the app. I'm not sure this is worth implementing, considering the tab support.
