### ISSUE TITLE
Include recent articles in new tab

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#75]
Include a few recent articles in the new tab page.

In web browsers such as Firefox, Edge, and Chrome the new tab page includes links.

On the new tab page Wike could include a handful recent articles and maybe a handful of random bookmarked articles.

**Comment by hugolabe** [comment]
I think the new tab page could be improved, though I wouldn't want it to be too cluttered. Maybe add a link or button to access recent articles?

I will think more on the subject.

**Comment by vanillajonathan** [comment]
I think it is a good idea to try to keep it relatively clean, but I think that adding buttons or links is not going to provide much value because I think since it requires an extra click users are not likely to click on them. I think a better approach would be to provide some content up front that gives a glance, and possibly have an option to toggle the visibility of that content.

In the new page in Firefox you have a gear icon in the top-right corner that presents you with switches to toggle the visibility of the content.
https://support.mozilla.org/en-US/kb/customize-items-on-firefox-new-tab-page#w_show-more-or-fewer-shortcuts

**Comment by hugolabe** [comment]
In version 2 the new tab page has been changed and now uses Adw.StatusPage, with two buttons that open the main page or a random article. In this way it’s closer to what other GTK applications do when they have no content to display. And, on the other hand, now the history is directly accessible in the sidebar.
