### ISSUE TITLE
[Feature Request] Offline Support/ Kiwix integration

### ISSUE THREAD

**Issue by ykhurshid** [hugolabe/Wike#78]
Would be nice if you could have an option for Wike to access an offline archive of wikipedia, such as a zim file.

**Comment by hugolabe** [comment]
This is outside of the application goals.

Accessing that type of content is a completely different thing to how Wike works today and would require an almost complete rewrite of the app.

There are already [other applications](https://flathub.org/apps/details/org.kiwix.desktop) that serve this purpose.
