### ISSUE TITLE
going back in page history does not reload theme

### ISSUE THREAD

**Issue by janxkoci** [hugolabe/Wike#82]
Very nice app, very useful, thank you for it.

I noticed this tiny issue, where I got a page with wrong theme after changing it and navigating back in history.

## Steps to reproduce

1. open some article
2. click any link to navigate to a new article
3. after loading new article, change theme (e.g. from dark to sepia)
4. return back to previous article
   - here you see the old theme
6. go to different article - theme is back to the new one

## Screenshot
Here is a screenshot of a popover menu with a new theme selected, but article having different (old) theme. Notice the history arrows, indicating how we got here.

![Snímek z 2022-05-16 19-10-38](https://user-images.githubusercontent.com/19331850/168647912-73952fad-34ac-4c77-94b5-a74c8724f17c.png)

Also note that the article in the other tab reloaded the theme properly, so no such issue there.

**Comment by hugolabe** [comment]
Thank you!

It's true. This is because when using the navigation buttons, webkit loads the pages from the cache.

Fixed in commit 715908a76a4d692bdd3c2356e97e2327bc0d6b56

**Comment by janxkoci** [comment]
Yeah I thought so. Thanks for the fix :)

**Comment by janxkoci** [comment]
I can confirm the issue is fixed now.
