### ISSUE TITLE
Add support for wikiless

### ISSUE THREAD

**Issue by BirdInFire** [hugolabe/Wike#85]
Hello there, 

I just want to ask if it's possible for you to think about add support for wikiless (who is a portal for wikipedia).
(Yeah i know wiki don't spy on it's user if i have understood properly the concept of wikiless) it's to prevent those who use wikipedia for spying on them (because a vast amount of people use it) and if you check (for instance AIDS) on wikipedia it can disclose thing about you.

I would totally understand a refusal.

**Comment by hugolabe** [comment]
Sorry for the delay.

Giving support for wikiless would require so many changes in the application that seems unfeasible to me.

Wike uses the mobile wikipedia view (customized by CSS injection) to show the articles. Wikiless does not have a similar view.

On the other hand, the structure of the URLs is also different and this is essential for the internal operation of Wike.
