### ISSUE TITLE
Search by simply typing

### ISSUE THREAD

**Issue by Camiropan** [hugolabe/Wike#87]
It would be a nice feature to search for a new article by simply typing. 
Similar to Gnome Software, Gnome Settings, Gnome Files, etc.
As far as i can tell it would not conflict with any feature of Wike and it improves the keyboard-orientated user experience a lot.

**Comment by hugolabe** [comment]
This is duplicated: #28

**Comment by Camiropan** [comment]
Oh sorry. Then i will close the issue.
