### ISSUE TITLE
Libadwaita

### ISSUE THREAD

**Issue by Camiropan** [hugolabe/Wike#88]
Are there any plans to port Wike to Libadwaita?

**Comment by hugolabe** [comment]
Yes. The port to Libadwaita will arrive with version 2. Development is quite advanced, but there is currently no stable version of Webkit for GTK4 yet.

You can see some screenshot in other issues: #26 #65

**Comment by Camiropan** [comment]
Wow, that looks really impressive! 
thanks for your work!

**Comment by mossymossmoss** [comment]
Any update on this?

**Comment by hugolabe** [comment]
> Any update on this?

Version 2 is almost ready, but it depends on the stable version of Webkit 6, which will come with GNOME 44.

**Comment by bugaevc** [comment]
FWIW: https://discourse.gnome.org/t/webkitgtk-for-gtk-4-is-now-api-stable/14378

**Comment by rene-coty** [comment]
I think this issue can now be closed, as the GTK 4 port seems to be achieved.. One last suggestion before releasing version 2: you should make an announcement in This Week In Gnome 😁️

**Comment by hugolabe** [comment]
> One last suggestion before releasing version 2: you should make an announcement in This Week In Gnome

Yes, so far I haven't made announcements on TWIG, but I think it's a good idea :)
