### ISSUE TITLE
[Bug]  welcome to Wikipedia page is not in the user's language

### ISSUE THREAD

**Issue by werdahias** [hugolabe/Wike#91]
See [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020902) debian bug report.

**Comment by hugolabe** [comment]
> The Welcome to Wikipedia page is in English despite the user environment being set to French.

Yes, that is the normal behavior of the application. See #35

> It would be convenient to add the possibility to choose a default language when several are activated.

You can choose the default language in the search preferences popover (accessed by pressing the gear icon in the search entry). See #71

> Thanks and great application at all.

Thanks for using it!
