### ISSUE TITLE
Blurry text when zoomed in

### ISSUE THREAD

**Issue by SoEven** [hugolabe/Wike#93]
The font becomes blurry when zoomed in, to the point where it's much less readable.
![image](https://user-images.githubusercontent.com/24230012/196499431-fc6368ee-c38f-4ed7-8911-de5a3169b8dd.png)

**Comment by hugolabe** [comment]
I don't understand how you get that screenshot. Wike does not support page zoom.

**Comment by SoEven** [comment]
> I don't understand how you get that screenshot. Wike does not support page zoom.

All i did was pinch the touchpad of my lenovo laptop.
Also works using my Thinkpad touchscreen.

**Comment by hugolabe** [comment]
I work on a desktop computer that doesn't have a touchpad. However, I have tried it on a laptop and the same thing happens to me. It only happens in dark mode.

I don't think it can do much, since the rendering of the page is done by Webkit. In any case, I will try to investigate more on the subject.

**Comment by SoEven** [comment]
> I work on a desktop computer that doesn't have a touchpad. However, I have tried it on a laptop and the same thing happens to me. It only happens in dark mode.
> 
> I don't think it can do much, since the rendering of the page is done by Webkit. In any case, I will try to investigate more on the subject.

I do not expect you to fix it if it's a lot of work, I'm sure it's a very nieche feature.
Thanks for the feedback anyway!

**Comment by hugolabe** [comment]
In version 2 I have added a page zoom option in the view menu. In my case, the fonts look sharp even when fully zoomed in dark mode.

@SoEven Could you try it?
