### ISSUE TITLE
Wike forcefully defaults to English even if it is not among the enabled languages in the preferences, and there is no way to set the default language

### ISSUE THREAD

**Issue by nekohayo** [hugolabe/Wike#99]
I have configured Wike for people in developing countries, particularly children, who do not speak English. In the Wike languages settings, I have enabled only Spanish, or French and Spanish, but not English; yet, Wike defaults to displaying the English Wikipedia front page on startup, and searches in the English version of Wikipedia instead of the preferred language(s), which is unhelpful for those users.

Furthermore, I can also think of my 80-years-old aunts that would highly benefit from Wike but they do not speak a word of English, yet the application forces this language upon them, and they will never be able to "search for a valid English page first, then switch to an alternative language from there", it cannot work that way for them. It doesn't matter if non-English wikipedias are less complete, they do not speak English.

If we can't simply [use the system's language](https://github.com/hugolabe/Wike/issues/74), these users would need an option/preference for the "Default language for the homepage and search".

**Comment by hugolabe** [comment]
> these users would need an option/preference for the "Default language for the homepage and search"

This option already exists. You can change the active language by clicking the gear icon in the search entry and selecting the desired language in the popover. This selection affects both searches and home page.

![wike1-search-lang](https://user-images.githubusercontent.com/18441950/209564179-b6de3ebb-4379-4574-aa50-6290bb5a5201.png)

Maybe the option is a bit hidden. In Wike2 it will be shown in a more evident way.

![wike2-search-lang](https://user-images.githubusercontent.com/18441950/209564210-f1f7a9ce-377d-4a1c-a51f-811fcdeafaeb.png)

**Comment by nekohayo** [comment]
Ah yes, totally unnoticeable and undiscoverable in the current stable version of Wike. Your proposed UI from Wike2 is an improvement visually, I think, so in a way this may be considered solved. Will there be a provision in the Languages tab UI in the Settings dialog to set the default language, so that there's also that way to set it clearly?

**Comment by hugolabe** [comment]
It doesn't seem necessary to me. I think they are different things. The choice of languages ​​in preferences is something that normally you will only do the first time you use the application. On the other hand, the selection of the active language must be easily accessible if you use several languages.

Maybe it would be a good idea to have the active language selected automatically if you choose only one language in the preferences.
